name = "BoxWorld"
uuid = "3a8eabaa-ff0c-46c8-af7c-f38dcbb67fff"
authors = ["John Muchovej <5000729+jmuchovej@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
